### ISSUE TITLE
Download jammed on webfont

### ISSUE THREAD

**Issue by rickydazla** [internalfx/quickshot#10]
Not sure exactly which file but it was either a `.ttf` or `.svg` or `.eot` webfont file that caused this error:

```
/usr/local/lib/node_modules/quickshot/download.js:138
                        if (data.asset.attachment) {
                                ^
TypeError: Cannot read property 'asset' of undefined
    at /usr/local/lib/node_modules/quickshot/download.js:138:33
    at Deferrals.exports.Deferrals.Deferrals._call (/usr/local/lib/node_modules/quickshot/node_modules/iced-runtime/lib/runtime.js:86:16)
    at /usr/local/lib/node_modules/quickshot/node_modules/iced-runtime/lib/runtime.js:98:26
    at exports.trampoline.trampoline (/usr/local/lib/node_modules/quickshot/node_modules/iced-runtime/lib/runtime.js:64:14)
    at Deferrals.exports.Deferrals.Deferrals._fulfill (/usr/local/lib/node_modules/quickshot/node_modules/iced-runtime/lib/runtime.js:96:16)
    at Object.ret [as cb] (/usr/local/lib/node_modules/quickshot/node_modules/iced-runtime/lib/runtime.js:29:18)
    at /usr/local/lib/node_modules/quickshot/helpers.js:122:18
    at Deferrals.exports.Deferrals.Deferrals._call (/usr/local/lib/node_modules/quickshot/node_modules/iced-runtime/lib/runtime.js:86:16)
    at /usr/local/lib/node_modules/quickshot/node_modules/iced-runtime/lib/runtime.js:98:26
    at exports.trampoline.trampoline (/usr/local/lib/node_modules/quickshot/node_modules/iced-runtime/lib/runtime.js:64:14)
    at Deferrals.exports.Deferrals.Deferrals._fulfill (/usr/local/lib/node_modules/quickshot/node_modules/iced-runtime/lib/runtime.js:96:16)
```

**Comment by internalfx** [comment]
Would you mind installing the latest master branch and trying again?

**Comment by internalfx** [comment]
you can install the latest master from NPM by running `npm install -g internalfx/quickshot`

**Comment by rickydazla** [comment]
:zap:
