### ISSUE TITLE
quickshot configure fails

### ISSUE THREAD

**Issue by abrambailey** [internalfx/quickshot#32]
quickshot@2.1.1

```
➜  ~ qs configure
/usr/local/lib/node_modules/quickshot/bin/quickshot:3
let Promise = require('bluebird')
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:1003:3
```

**Comment by internalfx** [comment]
Quickshot requires node v6+

**Comment by abrambailey** [comment]
Thanks. Didn't realize I was so out of date!

**Comment by abrambailey** [comment]
Now I am seeing:

```
➜  ~ sudo npm rebuild node-sass
➜  ~ qs configure
/usr/local/lib/node_modules/quickshot/node_modules/node-sass/lib/index.js:15
    throw new Error(errors.missingBinary());
    ^

Error: Missing binding /usr/local/lib/node_modules/quickshot/node_modules/node-sass/vendor/darwin-x64-48/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 6.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 5.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to build the binding for your current environment.
    at Object.<anonymous> (/usr/local/lib/node_modules/quickshot/node_modules/node-sass/lib/index.js:15:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/quickshot/lib/theme/watch.js:13:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
```

**Comment by internalfx** [comment]
You need to completely clear out your old npm modules.

I can't remember exactly where osx keeps it....

Try this stackoverflow post.

http://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x

**Comment by internalfx** [comment]
You need to completely clear out your old npm modules.

I can't remember exactly where osx keeps it....

Try this stackoverflow post.

http://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x

**Comment by abrambailey** [comment]
Hey thanks again for your help. It's working beautifully ...

**Comment by internalfx** [comment]
Glad to hear it.

**Comment by trajce** [comment]
All right, this is what i did instead of removing all npm_modules.
I navigated to the global npm folder (on windows: `cd users\{username}\AppData\Roaming\npm` and there i executed `npm rebuild node-sass`
After that its all good.
