### ISSUE TITLE
let Promise = require('bluebird')

### ISSUE THREAD

**Issue by trajce** [internalfx/quickshot#34]
I'm receiving this error when i try to use quickshot in windows (i just updated to qs v2.1).
Before that i was using qs v1.3 without issues.

```
let Promise = require('bluebird')
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

**Comment by internalfx** [comment]
Duplicate #32 

See comments in that thread for fix
