### ISSUE TITLE
OSX Catalina issues

### ISSUE THREAD

**Issue by rickydazla** [internalfx/quickshot#66]
Using system node (6.x) I get this:

```
Rick@Nexus6 taylorstitch % qs config
/usr/local/lib/node_modules/quickshot/src/main.js:19
module.exports = async function (argv) {
                       ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/quickshot/bin/quickshot:5:12)
    at Module._compile (module.js:541:32)
```

Using NVM 7 I get this:

```
qs config
03:38:43 pm - SyntaxError: Unexpected token ...
=== START OF OUTPUT ===
/Users/Rick/.nvm/versions/node/v7.10.1/lib/node_modules/quickshot/src/requestify.js:45
      ...request,
      ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Rick/.nvm/versions/node/v7.10.1/lib/node_modules/quickshot/src/commands/config/targets.js:8:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
==== END OF OUTPUT ====

```

Any ideas??

**Comment by rickydazla** [comment]
Hmm... `nvm use 12` did the trick!
